<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
                http://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.polytech.app</groupId>
        <artifactId>leave-management-system</artifactId>
        <version>1.0</version>
    </parent>

    <artifactId>backend</artifactId>
    <packaging>pom</packaging>
    <name>Leave Management - Backend</name>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.polytech.app</groupId>
                <artifactId>core</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>com.polytech.app</groupId>
                <artifactId>jms</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>com.polytech.app</groupId>
                <artifactId>soap</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>com.polytech.app</groupId>
                <artifactId>web</artifactId>
                <version>${project.version}</version>
                <type>war</type>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <modules>
        <module>core</module>
        <module>jms</module>
        <module>soap</module>
        <module>web</module>
        <module>ear</module>
    </modules>

</project>
